export { default as Home } from '@compo/Home'
export { default as Footer } from '@layout/Footer'
export { default as Header } from '@layout/Header'
export { default as Compo } from '@compo/Compo'
export { default as Restaurants } from './restaurants'
export { default as OneRestaurant } from './OneRestaurant'
